# Generated by Django 5.2.7 on 2026-06-08 06:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachments',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
