# Generated by Django 5.2.7 on 2026-06-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0010_task_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('To Do', 'To Do'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
