# Generated by Django 5.2.7 on 2026-07-06 06:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0013_alter_notification_user_alter_tasktime_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('total_work_time', models.DurationField(default=datetime.timedelta)),
                ('status', models.CharField(choices=[('working', 'Working'), ('completed', 'Completed')], default='working', max_length=20)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clock_out__isnull', True)), fields=('user',), name='one_active_work_session_per_user')],
            },
        ),
    ]
