# Generated by Django 5.2.7 on 2026-07-06 12:22

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0014_worksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='screenshot')),
                ('reason', models.CharField(choices=[('periodic', 'Periodic'), ('idle', 'Idle'), ('manual', 'Manual')], default='periodic', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='work_track_admin.worksession')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
