# Generated by Django 5.2.7 on 2026-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0015_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_interval', models.PositiveIntegerField(default=300, help_text='Screenshot interval in seconds')),
                ('screenshot_retention_days', models.PositiveIntegerField(default=30, help_text='Delete screenshots after these many days')),
                ('idle_timeout', models.PositiveIntegerField(default=300, help_text='Idle timeout in seconds')),
                ('screenshot_enabled', models.BooleanField(default=True)),
                ('app_tracking_enabled', models.BooleanField(default=True)),
                ('website_tracking_enabled', models.BooleanField(default=True)),
                ('idle_tracking_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
