# Generated by Django 5.2.7 on 2026-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0016_monitoringsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='capture_quality',
            field=models.PositiveIntegerField(default=70, help_text='Screenshot JPEG quality (1-100)'),
        ),
    ]
