# Generated by Django 5.2.7 on 2026-07-07 12:22

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0017_monitoringsettings_capture_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('idle_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_sessions', to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_sessions', to='work_track_admin.worksession')),
            ],
            options={
                'ordering': ['-idle_start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idle_end_time__isnull', True)), fields=('user',), name='one_active_idle_session_per_user')],
            },
        ),
    ]
