# Generated by Django 5.2.7 on 2026-07-10 06:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0019_applicationusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=255)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('is_productive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_usage', to='work_track_admin.applicationusage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_usage', to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_usage', to='work_track_admin.worksession')),
            ],
            options={
                'ordering': ['-start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('user',), name='one_running_website_per_user')],
            },
        ),
    ]
