# Generated by Django 5.2.7 on 2026-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0020_websiteusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('attendance', 'Attendance'), ('idle', 'Idle'), ('application', 'Application'), ('website', 'Website'), ('screenshot', 'Screenshot'), ('system', 'System')], default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=150),
        ),
    ]
