# Generated by Django 5.2.7 on 2026-07-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0023_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
