# Generated by Django 5.2.7 on 2026-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0024_leavetype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
