# Generated by Django 5.2.7 on 2026-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0027_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('attendance', 'Attendance'), ('idle', 'Idle'), ('application', 'Application'), ('website', 'Website'), ('screenshot', 'Screenshot'), ('system', 'System'), ('leave_request', 'Leave Request'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled')], default='system', max_length=50),
        ),
    ]
