# Generated by Django 5.2.7 on 2026-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0028_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='Sender email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server (e.g.smtp.gmail.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password or App Password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
