# Generated by Django 5.2.7 on 2026-07-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0029_company_smtp_email_company_smtp_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='work_track_admin.company')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='leave_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='work_track_admin.leavepolicy'),
        ),
        migrations.CreateModel(
            name='LeavePolicyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_allowed', models.PositiveIntegerField()),
                ('carry_forward', models.BooleanField(default=False)),
                ('allow_half_day', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_details', to='work_track_admin.leavetype')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_details', to='work_track_admin.leavepolicy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(fields=('company', 'policy_name'), name='unique_leave_policy_per_company'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicydetail',
            constraint=models.UniqueConstraint(fields=('policy', 'leave_type'), name='unique_leave_type_per_policy'),
        ),
    ]
