# Generated by Django 5.2.7 on 2026-08-09 15:21

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0033_attendancecorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='company_logo'),
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_number', models.BooleanField(default=True)),
                ('require_special_character', models.BooleanField(default=True)),
                ('force_password_change_days', models.PositiveIntegerField(default=90)),
                ('session_timeout', models.PositiveIntegerField(default=30, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('account_lock_minutes', models.PositiveIntegerField(default=15)),
                ('enable_2fa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='work_track_admin.company')),
            ],
        ),
    ]
