# Generated by Django 5.2.7 on 2026-08-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0037_alter_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
