# Generated by Django 5.2.7 on 2026-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0039_alter_leavetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='blocked_applications',
            field=models.JSONField(blank=True, default=list, help_text='List of blocked application names that trigger an immediate screenshot'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='screenshot_on_blocked_app',
            field=models.BooleanField(default=True, help_text='Capture screenshot immediately when a blocked app is detected'),
        ),
        migrations.AlterField(
            model_name='monitoringsettings',
            name='capture_quality',
            field=models.PositiveIntegerField(default=90, help_text='Screenshot JPEG quality (1-100)'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='reason',
            field=models.CharField(choices=[('periodic', 'Periodic'), ('idle', 'Idle'), ('manual', 'Manual'), ('blocked_app', 'Blocked App')], default='periodic', max_length=20),
        ),
    ]
