# Generated by Django 5.2.7 on 2026-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_track_admin', '0040_monitoringsettings_blocked_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='est_hour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
